### ISSUE TITLE
bug: [execute error in quant_bert fine-tunning process for MRPC]

### ISSUE THREAD

**Issue by Shinonome233** [IntelLabs/nlp-architect#157]
When I run the following command to fine-tune Quantized BERT on MRPC,
nlp-train transformer_glue
--task_name mrpc
--model_name_or_path bert-base-uncased
--model_type quant_bert
--learning_rate 2e-5
--output_dir /tmp/mrpc-8bit
--evaluate_during_training
--data_dir /path/to/MRPC
--do_lower_case

 an error occurred like this:

Inference iteration: 100%|██████████████████████| 51/51 [01:19<00:00,  1.55s/it]
/Users/shinonomenano/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
2020-04-28 16:25:45,715 : INFO : ***** Evaluation results *****
2020-04-28 16:25:45,715 : INFO :   acc = 0.3161764705882353
2020-04-28 16:25:45,715 : INFO :   acc_and_f1 = 0.15808823529411764
2020-04-28 16:25:45,715 : INFO :   f1 = 0.0
None
Traceback (most recent call last):
  File "/Users/shinonomenano/opt/anaconda3/bin/nlp-train", line 5, in <module>
    nlp_train_cli()
  File "/Users/shinonomenano/opt/anaconda3/lib/python3.7/site-packages/nlp_architect/cli/__init__.py", line 45, in nlp_train_cli
    args.func(args)
  File "/Users/shinonomenano/opt/anaconda3/lib/python3.7/site-packages/nlp_architect/procedures/transformers/glue.py", line 46, in run_procedure
    do_training(args)
  File "/Users/shinonomenano/opt/anaconda3/lib/python3.7/site-packages/nlp_architect/procedures/transformers/glue.py", line 142, in do_training
    save_steps=args.save_steps,
  File "/Users/shinonomenano/opt/anaconda3/lib/python3.7/site-packages/nlp_architect/models/transformers/sequence_classification.py", line 135, in train
    save_steps=save_steps,
  File "/Users/shinonomenano/opt/anaconda3/lib/python3.7/site-packages/nlp_architect/models/transformers/base_model.py", line 356, in _train
    save_path=best_model_path,
  File "/Users/shinonomenano/opt/anaconda3/lib/python3.7/site-packages/nlp_architect/models/transformers/base_model.py", line 410, in update_best_model
    if i == 0 and f1 > best_dev:  # dev set
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Could you help me how to deal with that? Thanks a lot.

**Comment by peteriz** [comment]
Thanks for reporting, we'll push a fix soon

**Comment by Shinonome233** [comment]
> Thanks for reporting, we'll push a fix soon

The error is still existing. How could I solve it? Thanks for any of your suggestion.

**Comment by charliezjw** [comment]
I am getting this error as well. Is this any update? Thank you!

**Comment by charliezjw** [comment]
I submitted a merge request to fix the bug. https://github.com/IntelLabs/nlp-architect/pull/231

**Comment by peteriz** [comment]
Fixed in #231
